### ISSUE TITLE
`ModelInstance` için doküman oluşturulmalı

### ISSUE THREAD

**Issue by saracalihan** [anchovycation/metronom#30]
`Model` için yaptığımız gibi `ModelInstance` için de TSDocs daha kolay ve anlaşılır bir yazılım geliştirme süreci için doküman eklenmeli.

[ModelInstance.ts](https://github.com/anchovycation/metronom/blob/main/lib/ModelInstance.ts) içindeki fonksiyonlar, yapılar ve yaptıkları iş temelce şöyledir:
+ Fonksiyonlar
  + `constructor( data, model, dataInfo )`
    + ModelInstance sınıfının kurucu fonksiyonudur.
    + İçine ham veriyi, ait olduğu modeli, ve kardedilicek veri ile ilgili sistemsel bilgileri alır.
  + `save()`
    + Nesnenin şu anki halini Redis'e kaydeder.
  + `getPureData()`
    +  Nesne içindeki tüm metronomla ilgili verileri temizleyerek onu ham haline geri getirir.
  + `toJSON()`
    + nesneyi stringfy eder
+ Yapılar
  + `class` `ModelInstance`
  + `interface` `DataInfo`
    + kayıtla ilgili redis key'i gibi sistemsel verilerin tutulduğu yer
  + `interface` `ModelFields`
    + Metronomun işleyişinde kullandığı ve kayıt yada modelle ilgili bilgilerin tutulduğu yer

Buradaki tüm alanlar dokümante edilmelidir ve ardından oluşan doküman'ın doğruluğu incelenmelidir. 
Şurayı da inceleyebilirsiniz: #29

**Comment by beyzaerkan** [comment]
@saracalihan evet
