### ISSUE TITLE
Redis varsayılan ayarlar dışında kullanıldığında fazlaca kod tekrarı oluyor.

### ISSUE THREAD

**Issue by beyzaerkan** [anchovycation/metronom#42]
Redis'i varsayılan portunda veya diğer ayarlarında kullanılmadığında her model için bu ayarlar tekrar tekrar her model kurucusuna `ModelOptions`'a `redisClientOptions` olarak parametre geçilmesi gerekiyor.

### `Metronom` Sınıfı Eklenebilir
Bağlantı bilgilerinin ve diğer ana sistem bilgilerinin tutulacağı, buradan `define` adında bir fonksiyon ile  Model'e ilgili bilgilerin parametre olarak geçilebileceği bir sınıf yazılabilir.

Farklı ayarlar kullanılmak istendiğinde farklı bir nesne oluşturarak işlemler yapılabilir.

**Comment by saracalihan** [comment]
@beyzaerkan Model üreten fonksiyonun ismi ne olmalı sence? `create`, `define`, `createModel` veya farklı ne kullanabiliriz?

**Comment by beyzaerkan** [comment]
> @beyzaerkan Model üreten fonksiyonun ismi ne olmalı sence? `create`, `define`, `createModel` veya farklı ne kullanabiliriz?

`define` uygun görünüyor.

**Comment by saracalihan** [comment]
> > @beyzaerkan Model üreten fonksiyonun ismi ne olmalı sence? `create`, `define`, `createModel` veya farklı ne kullanabiliriz?
> 
> `define` uygun görünüyor.

Tamamdır, benim için de uygun görünüyor. Bu isimlendirme ile geliştirmeye devam edebiliriz

**Comment by saracalihan** [comment]
@beyzaerkan  senin için de uygunsa ben ilgileniyorum.
